config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :teacher_users
  devise_for :users
  get 'admin_panel/index'
  post 'admin_panel/index'
  get 'admin_panel/modify'
  post 'admin_panel/modify'
  get 'data_scraper/organize'
  post 'data_scraper/organize'
  get 'data_scraper/load'
  post 'data_scraper/load'
  get 'configuration/index'
  post 'configuration/index'
  get 'data_scraper/collect'
  post 'data_scraper/collect'
  root 'menu#index'
  get 'menu/index'
  post 'menu/index'
  get 'data_scraper/scrape'
  post 'data_scraper/scrape'
  get 'student_application/index'
  post 'student_application/index'
  get 'student_application/new'
  post 'student_application/new'
  get 'student_application/create'
  post 'student_application/create'
  get 'student_application/show'
  get  'student_application/edit'
  get 'student_application/update'
  put 'student_application/update'
  get 'student_application/delete'
  delete 'student_application/delete'
  get 'evaluations/show'
  post 'evaluations/show'
  get 'evaluations/new'
  post 'evaluations/new'
  get 'evaluations/index'
  post 'evaluations/index'
  get 'evaluations/create'
  post 'evaluations/create'
  delete 'evaluations/index' => 'evaluations#delete'
  get 'evaluations/destroy'
  get 'evaluations/update'
  put 'evaluations/update'
  get 'evaluations/edit'


  #get '/' =>'recommendations#new'
  get 'recommendations/list'
  get 'recommendations/new'
  get 'recommendations/show'
  get 'recommendations/edit'
  get 'recommendations/destroy'
  post 'recommendations/list'
  post 'recommendations/new'
  post 'recommendations/edit'
  get 'recommendations/create'
  post 'recommendations/create'
  #get 'recommendation/show'
  post 'recommendations/show'
  post 'recommendations/create' => 'recommendations#create'
  post 'recommendations/show' => 'recommendations#show'
  delete 'recommendations/show' => 'recommendations#delete'
  post 'recommendations/show' => 'recommendations#edit'
  post 'recommendations/update' => 'recommendations#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profiles/edit'

  get 'overall_login/choose_user'
  post 'overall_login/choose_user'
  get 'overall_login/choose_login'
  post 'overall_login/choose_login'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_name.rb
class ClassName < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :meetings, dependent: :delete_all
  has_and_belongs_to_many :graders
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  validates :grader_lname_dotnum, presence: true, format:{with: /\A[a-zA-Z]+\.[1-9]\d*\z/}
  validates :course, presence: true, numericality:{only_integer: true}, length: {is: 4}
end

app/models/grader.rb
class Grader < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_and_belongs_to_many :meetings
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_and_belongs_to_many :instructors
  belongs_to :course
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/student_recommend.rb
class StudentRecommend < ApplicationRecord
  validates :student_fname, presence: true, length: { in: 1..30 }
  validates :student_lname, presence: true, length: { in: 1..30 }
  # validates :teacher_fname, presence: true, length: { in: 1..30 }
  # validates :teacher_lname, presence: true, length: { in: 1..30 }
  validates :student_lname_num, numericality: { only_integer: true }
  # validates :teacher_lname_num, numericality: { only_integer: true }
  validates :course, presence: true, numericality:{only_integer: true}, length: {is: 4}
  #validates :course_section, allow_blank: true
  validates :course_specification, presence: true
  validates :semester, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/teacher_user.rb
class TeacherUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/teaching.rb
class Teaching < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_teacher_user!
  def list
  end

  def new
  end

  def create
    @recommend = StudentRecommend.new(user_params)
    if @recommend.save
      flash[:notice] = 'User saved successfully'
      flash[:alert] = ''
      @allrecommend = StudentRecommend.all
      render 'recommendations/show'
    else
      #Saving failed, we can inspect @user.errors for more information
      # flash[:alert] = 'User was not saved.'
      #flash[:alert] = @recommend.errors
      # redirect to form page again
      render 'recommendations/new'
    end
  end

  def show
     # use @ symbols if you want to use it the view
    @allrecommend = StudentRecommend.all
  end

  def edit
    @recommend = StudentRecommend.find(params[:id])
    render 'edit'
  end

  def update
     @recommend = StudentRecommend.find(params[:id])
     if @recommend.update(user_params)
       redirect_to :action => 'show', notice: 'Successfully updated the evaluation'
     else
       redirect_to :action => 'show', notice: 'Error updating the evaluation'
     end
  end

  def destroy 
    # i would add checks, just in case
    delete = StudentRecommend.find(params[:id])
    delete.destroy
    redirect_to :action => 'show', notice: 'Delete recommendation successful'
  end


  private
    def user_params
      params.require(:recommend).permit(:student_fname, :student_lname, :student_lname_num, :teacher_fname, :teacher_lname,  :teacher_lname_num, :course, :course_section, :semester, :course_specification)
    end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
  def get_recs(grader)
    rec_arr = []
    # array with last name and dot number
    ndn = grader.last_name_dot.split(".")
    # get all recommendations associated with student
    recs = StudentRecommend.where(student_lname: ndn[0].capitalize, student_lname_num: ndn[1]).or(StudentRecommend.where(student_lname: ndn[0], student_lname_num: ndn[1]))
    recs.each do |r|
      str = "Student has been "
      if r.course_specification.chomp == 'G'
        str.concat("generally recommended to grade #{r.course}")
      elsif r.course_specification.chomp == 'S'
        str.concat("specifically requested to grade #{r.course}, class number #{r.course_section},")
      end
      str.concat(" by #{r.teacher_fname} #{r.teacher_lname}.")
      rec_arr.push(str)
    end
    return rec_arr
  end

  def get_evals(grader)
    eval_arr = ["Evaluation scores out of 5:"]
    # get list of all evals of this student
    evals = Evaluation.where(grader_lname_dotnum: grader.last_name_dot)
    evals.each do |e|
      str = "#{e.course} -- Grading quality: #{e.quality} | Punctuality: #{e.punctuality}"
      str.concat(" | Communication: #{e.com_skills} | Knowledge: #{e.course_knowledge}")
      eval_arr.push(str)
    end
    return eval_arr
  end

  def enable_add(params)
    c = Course.find(params[:id])
    if c.graders.length().to_i == c.num_graders.to_i then return false end
    return true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluation_helper.rb
module EvaluationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/destroy.html.erb
<h1>Recommendations#destroy</h1>
<p>Find me in app/views/recommendations/destroy.html.erb</p>

app/views/recommendations/edit.html.erb
<!--<h1>Recommendations#edit</h1>-->
<!--<p>Find me in app/views/recommendations/edit.html.erb</p>-->
<!--# <h1>Recommendations#new</h1>-->
<!--# <p>Find me in app/views/recommendations/new.html.erb</p>-->
<!DOCTYPE html>
<html>

<head>
  <title>Edit Recommendation Form</title>
</head>
<body>

<h1>Edit Recommendation Form</h1>

<% if @recommend.nil? && @recommend.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recommend.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @recommend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<form action="/recommendations/update" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="id" value="<%=@recommend.id%>">
  <input type="hidden" id="teacher_fname" name="recommend[teacher_fname]" value="<%=current_teacher_user.f_name%>">
  <input type="hidden" id="teacher_lname" name="recommend[teacher_lname]" value="<%=current_teacher_user.l_name%>">
  <input type="hidden" id="teacher_lanem.#" name="recommend[teacher_lname_num]" value="<%=current_teacher_user.dot_num%>">

  <label for="student_fname">First Name:</label>
  <input type="text" id="student_fname" name="recommend[student_fname]" value="<%= @recommend.student_fname %>">
  <br>

  <label for="student_lname">Last Name:</label>
  <input type="text" id="student_lname" name="recommend[student_lname]" value="<%= @recommend.student_lname %>">
  <br>

  <label for="student_lname.#">Dot Number</label>
  <input type="text" id="student_lname.#" name="recommend[student_lname_num]" value="<%= @recommend.student_lname_num %>">
  <br>

<!--  <label for="teacher_fname">Instructor First Name:</label>-->
<!--  <input type="text" id="teacher_fname" name="recommend[teacher_fname]" value="<%#= @recommend.teacher_fname %>">-->
<!--  <br>-->

<!--  <label for="teacher_lname">Instructor Last Name:</label>-->
<!--  <input type="text" id="teacher_lname" name="recommend[teacher_lname]" value="<%#= @recommend.teacher_lname %>">-->
<!--  <br>-->

<!--  <label for="teacher_lname.#">Dot Number</label>-->
<!--  <input type="text" id="teacher_lname.#" name="recommend[teacher_lname_num]" value="<%#= @recommend.teacher_lname_num %>">-->
<!--  <br>-->

  <label for="course">Course Recommendation</label>
  <input type="text" id="course" name="recommend[course]" value="<%= @recommend.course %>">
  <br>

  <label for="course_section">Course Section (OPTIONAL):</label>
  <input type="text" id="course_section" name="recommend[course_section]" value="<%= @recommend.course_section %>">
  <br>

  <label for="semester">Future Semesters(FS) or Next Semester(NS)</label>
  <input type="text" id="semester" name="recommend[semester]" value="<%= @recommend.semester %>">
  <br>

  <label for="course_specification">General(G) or Specific(S) Endorsement</label>
  <input type="text" id="course_specification" name="recommend[course_specification]" value="<%= @recommend.course_specification %>">
  <br>

  <input type="submit" name="submit" class="submit">


</form>
<%= button_to 'Exit To Menu', menu_index_path%>
</body>


</html>

app/views/recommendations/list.html.erb
<!--<h1>Recommendations#list</h1>-->
<!--<p>Find me in app/views/recommendations/list.html.erb</p>-->

<!DOCTYPE html>
<body>
<head>
<title>Recommendation Form Option</title>
</head>
<%= button_to 'Exit To Menu', menu_index_path%>
<%= button_to 'Create a new form' , recommendations_new_path%>
<%= button_to 'Show all recommendations', recommendations_show_path%>
<%= button_to 'Delete a recommendation', recommendations_show_path%>
</body>
</html>

app/views/recommendations/new.html.erb
<!--# <h1>Recommendations#new</h1>-->
<!--# <p>Find me in app/views/recommendations/new.html.erb</p>-->
<!DOCTYPE html>
<html>

<head>
  <title>Recommendation Form</title>
</head>
<body>

<h1>Recommendation Form</h1>

<% if !@recommend.nil? && @recommend.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recommend.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @recommend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<form action="/recommendations/create" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" id="teacher_fname" name="recommend[teacher_fname]" value="<%=current_teacher_user.f_name%>">
  <input type="hidden" id="teacher_lname" name="recommend[teacher_lname]" value="<%=current_teacher_user.l_name%>">
  <input type="hidden" id="teacher_lanem.#" name="recommend[teacher_lname_num]" value="<%=current_teacher_user.dot_num%>">

  <label for="student_fname">First Name:</label>
  <input type="text" id="student_fname" name="recommend[student_fname]">
  <br>

  <label for="student_lname">Last Name:</label>
  <input type="text" id="student_lname" name="recommend[student_lname]">
  <br>

  <label for="student_lname.#">Dot Number</label>
  <input type="text" id="student_lname.#" name="recommend[student_lname_num]">
  <br>

  <label for="course">Course Recommendation</label>
  <input type="text" id="course" name="recommend[course]">
  <br>

   <label for="course_section">Course Section (OPTIONAL):</label>
   <input type="text" id="course_section" name="recommend[course_section]">
  <br>

  <label for="semester">Future Semesters(FS) or Next Semester(NS)</label>
  <input type="text" id="semester" name="recommend[semester]">
  <br>

  <label for="course_specification">General(G) or Specific(S) Endorsement</label>
  <input type="text" id="course_specification" name="recommend[course_specification]">
  <br>

  <input type="submit" name="submit" class="submit">

</form>

<br>

<%= button_to 'Exit To Menu', menu_index_path%>
</body>


</html>

app/views/recommendations/show.html.erb
<!--<h1>Recommendations#show</h1>-->
<!--<p>Find me in app/views/recommendations/show.html.erb</p>-->

<!DOCTYPE html>
<html>

<head>
  <title>List</title>
</head>
<body>
<%= button_to 'Exit To Menu', menu_index_path%>
<%= button_to 'Create a new form' , recommendations_new_path%>
<table>
  <tr>
    <th>Student First Name</th>
    <th>Student Last Name</th>
    <th>Student Dot Number</th>
    <th>Teacher First Name</th>
    <th>Teacher Last Name</th>
    <th>Teacher Dot Number</th>
    <th>Course</th>
    <th>Course Section</th>
    <th>Future Semester(FS) vs Next Semester(NS)</th>
    <th>General(G) or Specific(S) Endorsement</th>
    <th>Edit</th>
    <th>Delete</th>

  </tr>
  <% @allrecommend.each do |t| %>
    <tr>
      <td><%= t.student_fname %></td>
      <td><%= t.student_lname %></td>
      <td><%= t.student_lname_num %></td>
      <td><%= t.teacher_fname %></td>
      <td><%= t.teacher_lname %></td>
      <td><%= t.teacher_lname_num %></td>
      <td><%= t.course %></td>
      <td><%= t.course_section%></td>
      <td><%= t.semester %></td>
      <td><%= t.course_specification %></td>
      <td><%= link_to 'Edit', controller: 'recommendations', action: 'edit', id: t.id, method: :edit %></td>
      <td><%= link_to 'Delete', controller: 'recommendations', action: 'destroy', id: t.id, method: :delete %></td>
    </tr>
  <% end %>
</table>
</body>