config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :teacher_users
  devise_for :users
  get 'admin_panel/index'
  post 'admin_panel/index'
  get 'admin_panel/modify'
  post 'admin_panel/modify'
  get 'data_scraper/organize'
  post 'data_scraper/organize'
  get 'data_scraper/load'
  post 'data_scraper/load'
  get 'configuration/index'
  post 'configuration/index'
  get 'data_scraper/collect'
  post 'data_scraper/collect'
  root 'menu#index'
  get 'menu/index'
  post 'menu/index'
  get 'data_scraper/scrape'
  post 'data_scraper/scrape'
  get 'student_application/index'
  post 'student_application/index'
  get 'student_application/new'
  post 'student_application/new'
  get 'student_application/create'
  post 'student_application/create'
  get 'student_application/show'
  get  'student_application/edit'
  get 'student_application/update'
  put 'student_application/update'
  get 'student_application/delete'
  delete 'student_application/delete'
  get 'evaluations/show'
  post 'evaluations/show'
  get 'evaluations/new'
  post 'evaluations/new'
  get 'evaluations/index'
  post 'evaluations/index'
  get 'evaluations/create'
  post 'evaluations/create'
  delete 'evaluations/index' => 'evaluations#delete'
  get 'evaluations/destroy'
  get 'evaluations/update'
  put 'evaluations/update'
  get 'evaluations/edit'


  #get '/' =>'recommendations#new'
  get 'recommendations/list'
  get 'recommendations/new'
  get 'recommendations/show'
  get 'recommendations/edit'
  get 'recommendations/destroy'
  post 'recommendations/list'
  post 'recommendations/new'
  post 'recommendations/edit'
  get 'recommendations/create'
  post 'recommendations/create'
  #get 'recommendation/show'
  post 'recommendations/show'
  post 'recommendations/create' => 'recommendations#create'
  post 'recommendations/show' => 'recommendations#show'
  delete 'recommendations/show' => 'recommendations#delete'
  post 'recommendations/show' => 'recommendations#edit'
  post 'recommendations/update' => 'recommendations#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profiles/edit'

  get 'overall_login/choose_user'
  post 'overall_login/choose_user'
  get 'overall_login/choose_login'
  post 'overall_login/choose_login'
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :authenticate_admin!

  def index
    @filtered = filter_courses(params)
    @filter_opts = get_filter_opts(params)
  end

  def modify
    c = Course.find(params[:id])
    if params[:gr]
      if params[:rm] && c.graders.find_by(id: params[:gr]) != nil
        c.graders.delete(Grader.find(params[:gr]))
      elsif c.graders.find_by(id: params[:gr]) == nil
        c.graders.push(Grader.find(params[:gr]))

      end
    end
    @assigned = c.graders
    @filtered = filter_graders(params)
  end



  private

  def filter_courses(par)
    fc = Course.all

    if par[:course]
      if par[:course][:semester] != "All semesters"
        fc = fc.where(semester: par[:course][:semester])
      end
      if par[:course][:session] != "All sessions"
        fc = fc.where(session: par[:course][:session])
      end
      if par[:course][:name] != "All courses"
        fc = fc.select {|c| c.name[0, c.name.index(' ', 7)] == par[:course][:name]}
      end
      if par[:course][:open].to_i == 1
        fc = fc.select {|c| c.num_graders - c.graders.length() > 0}
      end
    end
    return fc
  end

  def filter_graders(params)
    filtered = []
    c = Course.find(params[:id])
    # get the className id
    cn_id = ClassName.find_by(name: c.name)

    meeting_times = []
    # get the list of times that this class meets
    c.meetings.each {|m| meeting_times.push(m.time)}

    graders_list = Grader.all
    graders_list.each do |g|
      if c.graders.find_by(id: g.id) == nil
        # check if course is complete
        completed = GraderCompletedCourse.find_by(grader_id: g.id, course_id: cn_id)
        # check for availability
        if completed != nil
          if !c.attendance
            filtered.push(g) # if attendance is not required, they are eligible
          else
            times = []
            GraderTimeAvailability.where(grader_completed_course_id: completed.id).each do |t|
              times.push(t.time)
            end
            if (meeting_times - times).empty?
              filtered.push(g) # grader is eligible if they are available
            end
          end
        end
      end
    end
    return filtered
  end

  def get_filter_opts(par)
    filters = {
      sem: ["All semesters"],
      name: ["All courses"],
      ses: ["All sessions"],
      open: [ ["Courses with and without open positions", 0], ["Only courses with open positions", 1] ]
    }

    filters[:sem] = Course.distinct.pluck(:semester)
    filters[:name] = Course.distinct.pluck(:name)
    filters[:name].map! {|n| n[0, n.index(' ', 7)]}
    filters[:ses] = Course.distinct.pluck(:session)

    filters[:sem].unshift("All semesters")
    filters[:name].unshift("All courses")
    filters[:ses].unshift("All sessions")

    # if parameters have been passed, the active filter should be the top option
    if par[:course]
      filters[:sem].unshift(par[:course][:semester])
      filters[:name].unshift(par[:course][:name])
      filters[:ses].unshift(par[:course][:session])
      if par[:course][:open].to_i == 1
        filters[:open].reverse!
      end
    end

    filters[:sem] = filters[:sem].uniq
    filters[:name] = filters[:name].uniq
    filters[:ses] = filters[:ses].uniq

    return filters
  end

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
  def get_recs(grader)
    rec_arr = []
    # array with last name and dot number
    ndn = grader.last_name_dot.split(".")
    # get all recommendations associated with student
    recs = StudentRecommend.where(student_lname: ndn[0].capitalize, student_lname_num: ndn[1]).or(StudentRecommend.where(student_lname: ndn[0], student_lname_num: ndn[1]))
    recs.each do |r|
      str = "Student has been "
      if r.course_specification.chomp == 'G'
        str.concat("generally recommended to grade #{r.course}")
      elsif r.course_specification.chomp == 'S'
        str.concat("specifically requested to grade #{r.course}, class number #{r.course_section},")
      end
      str.concat(" by #{r.teacher_fname} #{r.teacher_lname}.")
      rec_arr.push(str)
    end
    return rec_arr
  end

  def get_evals(grader)
    eval_arr = ["Evaluation scores out of 5:"]
    # get list of all evals of this student
    evals = Evaluation.where(grader_lname_dotnum: grader.last_name_dot)
    evals.each do |e|
      str = "#{e.course} -- Grading quality: #{e.quality} | Punctuality: #{e.punctuality}"
      str.concat(" | Communication: #{e.com_skills} | Knowledge: #{e.course_knowledge}")
      eval_arr.push(str)
    end
    return eval_arr
  end

  def enable_add(params)
    c = Course.find(params[:id])
    if c.graders.length().to_i == c.num_graders.to_i then return false end
    return true
  end

end

app/views/admin_panel/index.html.erb
<!-- Created by Jing George 4/10/2020 -->

<%= button_to 'Back to Menu', menu_index_path %>
<h1> Administrator Panel </h1>

<!-- options to filter courses from the big list -->
<div id="filters">
  <!-- Filtering adapted from
  https://forum.upcase.com/t/how-to-implement-filtering-for-my-rails-app/2834/2
  -->
  <%= form_tag admin_panel_index_path, method: "get" do %>
    <%= select "course", "semester", options_for_select(@filter_opts[:sem], selected: params[:semester]) %>
    <%= select "course", "name", options_for_select(@filter_opts[:name], selected: params[:name]) %>
    <%= select "course", "session", options_for_select(@filter_opts[:ses], selected: params[:session]) %>
    <%= select "course", "open", options_for_select(@filter_opts[:open], selected: params[:open]) %>
    <%= submit_tag "Filter", name: nil %>
  <% end %>
</div>

<!-- display courses -->
<div id="course_list">

  <% if @filtered.empty? %>
    <h3>No courses match the filters applied.</h3>
  <% else %>
    <% @filtered.each do |c| %>

      <div class="course">
        <div class="row">
        <div class="title"><%= c.name %>, Class #<%= c.class_num %></div>
        <!-- link to assign grader and make other changes -->
        <div class="edit"><a href="/admin_panel/modify?id=<%= c.id %>">Edit</a></div>
        <div class="clear"></div>
        </div>

        <div class="row">
        <div class="sem">Semester: <%= c.semester %></div>
        <div class="ses">Session: <%= c.session %></div>
        <div class="comp">Component: <%= c.component %></div>
        <div class="clear"></div>
        </div>

        <div class="row">
        <% if c.attendance %>
        <i> ** This class requires grader attendance ** </i><br/>
        <% end %>
        <%= c.num_graders - c.graders.length() %> of <%= c.num_graders %> grading positions open.
         Graders assigned: <%= c.graders.pluck(:name).join('; ') %>
        </div>

        <!-- for each meeting print a row -->
        <% c.meetings.each do |m| %>
        <div class ="row">
        <% loc = m.location %>
        <% if loc == " " then loc = "Location N/A" end %>
        <div class="loc"><%= loc %></div>
        <div class="time"><%= m.time %></div>
        <div class="instr"><%= m.instructors.pluck(:name).join('; ') %></div>
        <div class="clear"></div>
        </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/admin_panel/modify.html.erb
<!-- Created by Jing George 4/10/2020 -->

<%= button_to 'Back to Administrator Panel', admin_panel_index_path %>

<% c = Course.find(params[:id]) %>

<h2>Modify <%= c.name %>, Class #<%= c.class_num %></h2>
<p>
  Semester: <%= c.semester %> | Session: <%= c.session %> | Component: <%= c.component %>
  <% if c.attendance %>
  <i> | ** This class requires grader attendance ** </i><br/>
  <% end %>
</p>
<p>
<%= c.num_graders - c.graders.length() %> of <%= c.num_graders %> grading positions open.
   Graders assigned: <%= c.graders.pluck(:name).join('; ') %>
</p>

<!-- for each meeting print a row -->
<% c.meetings.each do |m| %>
<% loc = m.location %>
<% if loc == " " then loc = "Location N/A" end %>
<div class ="row">
<div class="loc"><%= loc %></div>
<div class="time"><%= m.time %></div>
<div class="instr"><%= m.instructors.pluck(:name).join('; ') %></div>
<div class="clear"></div>
</div>
<% end %>
<br/>

<% if @assigned.length() > 0 %>
<h2>Assigned graders: </h2>
<div class="grader_list">
<% @assigned.each do |g| %>
  <div class="grader">
    <div class="row">
      <div class="title"><%= g.name %>, <%= g.last_name_dot %></div>
      <% if g.courses.find_by(semester: Course.find(params[:id]).semester) != nil %>
      <div class="message">Student is already assigned to a class in
        <%= Course.find(params[:id]).semester %>.</div>
      <% end %>
    <div class="button2">
    <%= button_to "Remove from class", admin_panel_modify_path(rm: 1, id: params[:id], gr: g.id)%>
    </div>
    <div class="clear"></div></div>

    <div class="row">
      <% cn = ClassName.find_by(name: Course.find(params[:id]).name) %>
      Grade in <%= cn.name %>:
      <%= GraderCompletedCourse.find_by(grader_id: g.id, course_id: cn.id).grade %>
    <div class="clear"></div></div>

    <div class="row">
      GPA: <%= g.gpa %>
    <div class="clear"></div></div>

    <div class="row">
      <% get_recs(g).each do |r| %>
        <%= r %><br/>
      <% end %>
    <div class="clear"></div></div>

    <div class="row">
      <% get_evals(g).each do |e| %>
        <%= e %><br/>
      <% end %>
    <div class="clear"></div></div>
  </div>
<% end %>
</div>
<% end %>


<h2>Available graders: </h2>
<div class="grader_list">
<% if @filtered.empty? %>
  <h3>There are no eligible candidates to grade this class.</h3>
<% else %>
  <% @filtered.each do |g| %>
    <div class="grader">
      <div class="row">
        <div class="title"><%= g.name %>, <%= g.last_name_dot %></div>
        <% if g.courses.find_by(semester: Course.find(params[:id]).semester) != nil %>
        <div class="message">Student is already assigned to a class in
          <%= Course.find(params[:id]).semester %>.</div>
        <% end %>
      <div class="button2">
        <% if enable_add(params) %>
      <%= button_to "Assign to class", admin_panel_modify_path(id: params[:id], gr: g.id)%>
      <% end %>
      </div>
      <div class="clear"></div></div>

      <div class="row">
        <% cn = ClassName.find_by(name: Course.find(params[:id]).name) %>
        Grade in <%= cn.name %>:
        <%= GraderCompletedCourse.find_by(grader_id: g.id, course_id: cn.id).grade %>
      <div class="clear"></div></div>

      <div class="row">
        GPA: <%= g.gpa %>
      <div class="clear"></div></div>

      <% if get_recs(g).length() > 0 %>
      <div class="row">
        <% get_recs(g).each do |r| %>
          <%= r %><br/>
        <% end %>
      <div class="clear"></div></div>
      <% end %>

      <% if get_evals(g).length() > 1 %>
      <div class="row">
        <% get_evals(g).each do |e| %>
          <%= e %><br/>
        <% end %>
      <div class="clear"></div></div>
      <% end %>

    </div>
  <% end %>
<% end %>
</div>