config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :teacher_users
  devise_for :users
  get 'admin_panel/index'
  post 'admin_panel/index'
  get 'admin_panel/modify'
  post 'admin_panel/modify'
  get 'data_scraper/organize'
  post 'data_scraper/organize'
  get 'data_scraper/load'
  post 'data_scraper/load'
  get 'configuration/index'
  post 'configuration/index'
  get 'data_scraper/collect'
  post 'data_scraper/collect'
  root 'menu#index'
  get 'menu/index'
  post 'menu/index'
  get 'data_scraper/scrape'
  post 'data_scraper/scrape'
  get 'student_application/index'
  post 'student_application/index'
  get 'student_application/new'
  post 'student_application/new'
  get 'student_application/create'
  post 'student_application/create'
  get 'student_application/show'
  get  'student_application/edit'
  get 'student_application/update'
  put 'student_application/update'
  get 'student_application/delete'
  delete 'student_application/delete'
  get 'evaluations/show'
  post 'evaluations/show'
  get 'evaluations/new'
  post 'evaluations/new'
  get 'evaluations/index'
  post 'evaluations/index'
  get 'evaluations/create'
  post 'evaluations/create'
  delete 'evaluations/index' => 'evaluations#delete'
  get 'evaluations/destroy'
  get 'evaluations/update'
  put 'evaluations/update'
  get 'evaluations/edit'


  #get '/' =>'recommendations#new'
  get 'recommendations/list'
  get 'recommendations/new'
  get 'recommendations/show'
  get 'recommendations/edit'
  get 'recommendations/destroy'
  post 'recommendations/list'
  post 'recommendations/new'
  post 'recommendations/edit'
  get 'recommendations/create'
  post 'recommendations/create'
  #get 'recommendation/show'
  post 'recommendations/show'
  post 'recommendations/create' => 'recommendations#create'
  post 'recommendations/show' => 'recommendations#show'
  delete 'recommendations/show' => 'recommendations#delete'
  post 'recommendations/show' => 'recommendations#edit'
  post 'recommendations/update' => 'recommendations#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profiles/edit'

  get 'overall_login/choose_user'
  post 'overall_login/choose_user'
  get 'overall_login/choose_login'
  post 'overall_login/choose_login'
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
  def index
    @courses = []
    @properties = []
    @prop_hash = {}
    @with = "with"
    if params[:grouping]
      if params[:grouping][:inclusion] == "do not meet" then @with = "without" end

      check_sem = params[:semester].chomp.match(/^(((AU|SP|SU)\d{2}[,][ ])*)(AU|SP|SU)\d{2}$/)
      check_com = params[:component].chomp.match(/^(((LAB|LEC|REC)[,][ ])*)(LAB|LEC|REC)$/)
      check_num = params[:class_num].chomp.match(/^((\d{4,5}[,][ ])*)\d{4,5}$/)
      check_nam = params[:name].chomp.match(/^((\d{4}([H]?|[.]\d{2}[H]?)[,][ ])*)\d{4}([H]?|[.]\d{2}[H]?)$/)

      puts params
      if !check_sem && params[:semester].chomp != ""
        redirect_to action: 'index', alert: 'Semesters must be formatted as a 2-letter 2-digit code,
        separated by a comma and space if multiple.'
        return
      elsif !check_com && params[:component].chomp != ""
        redirect_to action: 'index', alert: 'Components must be formatted as a 3-letter code,
        separated by a comma and space if multiple.'
        return
      elsif !check_num && params[:class_num].chomp != ""
        redirect_to action: 'index', alert: 'Invalid class number format.'
        return
      elsif !check_nam && params[:name].chomp != ""
        redirect_to action: 'index', alert: 'Invalid number-in-name format.'
        return
      end
      organize_properties(params)
      find_courses(params)

    end
    update = 0
    if params[:config] # update the configuration for the found classes
      @courses.each {|c| Course.find(c.id).update(num_graders: params[:config][:num_g].to_i)}
      @courses.each {|c| Course.find(c.id).update(graders: Course.find(c.id).graders.take(params[:config][:num_g].to_i))}
      update = 1
    end
    if params[:attend] == "true"
      @courses.each {|c| Course.find(c.id).update(attendance: true)}
      update = 1
    elsif params[:attend] == "false"
      @courses.each {|c| Course.find(c.id).update(attendance: false) }
      update = 1
    end
    if update == 1
      puts @courses
      @courses.each {|c| puts Course.find(c.id).attendance}
      str = "Courses " + @with + " the properties " + @properties.join(", ") + " successfully updated."
      redirect_to action: 'index', notice: str
      return
    end

  end # end index

  private

  def organize_properties(params)
    # name is not included since the input name is only part of the recorded name
    sym_arr = ["semester", "component", "class_num", "name"]
    params.each do |k, v|
      if sym_arr.include?(k) && params[k]
        temp = v.split(", ")
        if !temp.empty?
          if k != "name" then @prop_hash[k] = temp end
          @properties.append(temp)
        end
      end
    end # end each
    if @prop_hash.key?("class_num")
      @prop_hash["class_num"].map!(&:to_i)
    end
  end # end organize_properties

  def find_courses(params)
    if params[:grouping][:inclusion] == "meet"
      @courses = Course.where(@prop_hash)
      if !params[:name].empty?
        @courses = @courses.select {|c| !(c.name.split(" ") & params[:name].split(", ")).empty?}
      end
    else
      @courses = Course.where.not(@prop_hash)
      if !params[:name].empty?
        @courses = @courses.select {|c| (c.name.split(" ") & params[:name].split(", ")).empty?}
      end
    end

  end # end find_courses
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/views/configuration/index.html.erb
<%= button_to "Back to menu", menu_index_path %>
<h1> Configuration </h1>

<h3>Run web scraper to update and overwrite courses (this will overwrite all course info, including current grader assignments)</h3>
<%= button_to 'Update and overwrite', data_scraper_scrape_path %>

<h3>Run web scraper to collect new courses (this will only add new course info and will not overwrite anything)</h3>
<%= button_to 'Collect new courses', data_scraper_collect_path %>

<h3>View or create a configuration</h3>

<%= form_tag configuration_index_path, method: "post" do %>
  <p>I want to change the configuration for all classes that
  <%= select "grouping", "inclusion", options_for_select(["meet", "do not meet"], selected: params[:inclusion]) %>
   the following criteria:</p>
   <p>*** Leave a field blank if no preference. ***</p>
   <p>*** To list multiple identifiers of one type, separate each by a comma and space.
     Example: 3901, 3902, 3903 ***</p>

  <% if params[:alert] %>
  <p id="alert">Alert: <%= params[:alert] %></p>
  <% end %>

  <div id="criteria">
  <div class="block">
  <%= label_tag(:semester, "Semester (ex: SU20):") %>
  <%= text_field_tag(:semester) %>
  </div><div class="block">
  <%= label_tag(:component, "Component (ex: LAB):") %>
  <%= text_field_tag(:component)%>
  </div><div class="block">
  <%= label_tag(:class_num, "Class number (unique):") %>
  <%= text_field_tag(:class_num) %>
  </div><div class="block">
  <%= label_tag(:name, "Number in name (ex: 2221):") %>
  <%= text_field_tag(:name)%>
  </div>
  </div>

  <div id="config">
  <div class="block">
  <%= label_tag(:num_g, "Number of graders:") %>
  <%= select "config", "num_g", options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8"], selected: params[:num_g]) %>
  </div><div class="button">
  <%= radio_button_tag(:attend, "true") %>
  </div><div class="block">
  <%= label_tag(:attend_true, "Grader attendance is required") %>
  </div><div class="button">
  <%= radio_button_tag(:attend, "false") %>
  </div><div class="block">
  <%= label_tag(:attend_false, "Grader attendance is not required") %>
  </div><div class="block">
<%= submit_tag "Update", name: nil %></div>
</div>
<% end %>

<% if params[:notice] %>
<p id="notice"><%= params[:notice] %></p>
<% end %>


<div id="result">
  <p>
    <% @courses.sort_by(&:class_num).each do |c| %>
      Class #<%= c.class_num %>,
      <%= c.name %>, <%= c.num_graders %> grading positions,
      attendance required: <%= c.attendance %><br/>
    <% end %>
  </p>
</div>